export const DEFAULT_ND = "N/D";
export const KEEP_ALIVE_TIMER = 5 * 60 * 1000; // 5 minutes
export const KEEP_ALIVE_API_TIMER = 2 * 60 * 1000; // 2 minutes
export const COUNTDOWN_TIMER = 66 * 1000; // 1 minute and 6 seconds
export const WAITING_POLLING_INTERVAL = 10 * 1000; // 10 seconds
export const WAITING_POLLING_TIMEOUT = 3 * 60 * 1000; // 3 minutes
export const FIRMWARE_POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const DELAY_FIRMWARE_LOGIN = 6 * 1000; // 5 seconds
export const POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const SHORT_POLLING_INTERVAL = 100; // 100 milliseconds
export const POLLING_TIMEOUT = 5 * 60 * 1000; // 5 minutes
export const REPLACE_POLLING_INTERVAL = 1000; // 1 second
export const RESET_POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const LEARN_KEYS_POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const SEARCH_POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const DELAY_TO_LOGOUT = 1000; // 1 second
export const DELAY_TO_LOGOUT_UPDATE = 5 * 1000; // 5 seconds
export const UPDAATE_VOCALS_POLLING_INTERVAL = 3 * 1000; // 3 seconds
export const TIME_TO_RESTART_INTERNAL_PROCESSES = 8 * 1000; // 5 seconds
export const CONTEXT_FIELD = "__context__";
export const COMMON_DATA_FIELD = "__commonData__";
export const DEFAULT_THEME_NAME = "default";
export const DATETIME_LOCAL_FORMAT = "YYYY-MM-DDTHH:mm";
export const TIME_FORMAT = "HH:mm:ss";
export const AXIOS_TIMOUT_ERROR = "ECONNABORTED";
export const MAX_UP_FILE_SIZE_SW = 33000000; // 33 MB
export const MAX_CFG_FILE_SIZE = 500000; // 500 KB
export const FOUND_DEVICES_ID_FIELD = "id";
export const FOUND_DEVICES_DESCRIPTION_FIELD = "description";
export const LEARN_KEYS_ID_FIELD = "Id";
export const LEARN_KEYS_DUPLICATED_FIELD = "Duplicated";
export const LEARN_KEYS_DESCRIPTION_FIELD = "Description";
export const PIN_LENGTH = 6;
export const ROW_TOOLTIP_DELAY = 1000; // 1 second
export const FALLBACK_LANGUAGE = "en";
